### COLOCAR SU TOKEN EN EL AUTHORIZATION
### PARA PODER HACER REQUEST A LAS RUTAS PROTEGIDAS

#### GET all Roles
GET http://localhost:3000/api/roles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJyb0BnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTcxNzc4ODg5MCwiZXhwIjoxNzE3NzkyNDkwfQ.UblRA7HuCmhwaV6nTr011vFzw6wx8rPz0f02zFKrurk


#### GET role by Id
GET http://localhost:3000/api/roles/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJyb0BnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTcxNzc4ODg5MCwiZXhwIjoxNzE3NzkyNDkwfQ.UblRA7HuCmhwaV6nTr011vFzw6wx8rPz0f02zFKrurk



#### POST role
POST http://localhost:3000/api/roles HTTP/1.1
Content-Type: application/json

{  "name": "admin" }

#### PUT roles
PUT http://localhost:3000/api/roles/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJyb0BnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTcxNzc4ODg5MCwiZXhwIjoxNzE3NzkyNDkwfQ.UblRA7HuCmhwaV6nTr011vFzw6wx8rPz0f02zFKrurk

{  "name": "admin "}

#### DELETE roles

DELETE http://localhost:3000/api/roles/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJyb0BnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTcxNzc4ODg5MCwiZXhwIjoxNzE3NzkyNDkwfQ.UblRA7HuCmhwaV6nTr011vFzw6wx8rPz0f02zFKrurk
